export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


import './globals.css';
import MainHeader from '../components/MainHeader';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-blue-100">
        <MainHeader />
        <div className="container mx-auto max-w-6xl py-8">
          {children}
        </div>
      </body>
    </html>
  )
}
